version: 2
project_name: mysql-router-exporter
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: mysql-router-exporter
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
release:
  github:
    owner: community-artifacts
    name: mysql-router-exporter
  prerelease: false
